### ISSUE TITLE
2016-xx-xx : Symfony User Group Belgium meetup

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#4]
**Contact** : Jean-Christophe Cuvelier (@totophe)
**Talk 1** :
**Talk 2** :
**Meetup page** : ?
**Tweet** : ?
**Joind.in page** : ?
**RSVP rate** : ?/50
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [ ] share on social media
- [ ] notify concierge
- [ ] order food / drinks
- [ ] share parking space image on social media
- [ ] ug flyers with directions
- [x] ...
- [ ] profit!
