### ISSUE TITLE
2016-xx-xx : PHP Benelux meetup

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#6]
**Contact** : Michelangelo van Dam (@Dragonbe)
**Talk 1** :
**Talk 2** :
**Meetup page** : ?
**Tweet** : ?
**Joind.in page** : ?
**RSVP rate** : ?/50
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [ ] share on social media
- [ ] notify concierge
- [ ] order food / drinks
- [ ] share parking space image on social media
- [ ] ug flyers with directions
- [x] ...
- [ ] profit!

**Comment by TSchuermans** [comment]
Cancelled due to: https://twitter.com/DragonBe/status/703202677732286464
