### ISSUE TITLE
2016-02-25 : Fronteers meetup

### ISSUE THREAD

**Issue by TSchuermans** [nucleus-be/office-meetups#7]
**Contact** : Ibe Vanmeenen (@IbeVanmeenen)
**Talk 1** : Mattias Geniar (@mattiasgeniar) - HTTP/2: The Next Version of the Internet
**Talk 2** : Koen Kivits (@koenkivits) - Bowser in de browser
**Meetup page** : https://fronteers.nl/bijeenkomsten/2016/nucleus
**Tweet** : https://twitter.com/nucleus_hosting/status/700238975831830528
**Joind.in page** : /
**RSVP rate** : 6/50
**Parking space** :
![Parking space](https://raw.githubusercontent.com/nucleus-be/office-meetups/master/parking_space.png)

**Todo** :
- [x] share on social media
- [x] notify concierge
- [x] order food / drinks
- [ ] share parking space image on social media
- [ ] ug flyers with directions
- [x] ...
- [x] profit!
